### ISSUE TITLE
version needs to be updated in release 2.2.2

### ISSUE THREAD

**Issue by paukstelis** [synman/Octoprint-Bettergrblsupport#101]
The old 'version loop' bug has popped up with 2.2.2. setup.py needs to be updated.

**Comment by synman** [comment]
Are you in the stable or release candidate channel?

**Comment by paukstelis** [comment]
stable

**Comment by synman** [comment]
I'm not seeing this....

![Screenshot_20221120-102943](https://user-images.githubusercontent.com/1299716/202910847-b508a8bd-089d-42cd-955b-f9c8c360ee1f.png)

**Comment by synman** [comment]
Ah, so you are stuck in 2.2.1?

**Comment by paukstelis** [comment]
Yes, it says I am stuck because setup.py in the release zip file (https://github.com/synman/Octoprint-Bettergrblsupport/archive/refs/tags/2.2.2.zip) has version as 2.2.1.

**Comment by paukstelis** [comment]
![image](https://user-images.githubusercontent.com/28326982/202911038-36f65d53-cb12-4d9b-a7df-23ec58f8d16d.png)

**Comment by synman** [comment]
Did I forget to push to master?

Omg... I bet that is what it is.  And I'm fine because I pushed from RC.

Stand by.

**Comment by synman** [comment]
yup... should be all better now... thanks for the reminder :)

<img width="336" alt="Screenshot 2022-11-20 at 10 42 29 AM" src="https://user-images.githubusercontent.com/1299716/202911535-b8b702d5-d402-48db-bf0b-86a4fb959f95.png">
