### ISSUE TITLE
Issue when upgrading

### ISSUE THREAD

**Issue by championwescott** [synman/Octoprint-Bettergrblsupport#102]
Could just be my setup, but whenever I tried to upgrade to 2.2.2 using the OctoPrint Plugin Manager, it re-installed 2.2.1.

So instead of letting it run 
`/home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install https://github.com/synman/OctoPrint-Bettergrblsupport/archive/2.2.2.zip --no-cache-dir`

 I just ran 

`/home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install https://github.com/synman/OctoPrint-Bettergrblsupport/archive/2.2.2.zip --no-cache-dir`

instead.  That installed without issue.

**Comment by synman** [comment]
I thought I fixed this with #101 but will re-review.

**Comment by synman** [comment]
this should be fixed now.

**Comment by championwescott** [comment]
Thanks!
