### ISSUE TITLE
can only have one printer profile

### ISSUE THREAD

**Issue by max0r4axor** [synman/Octoprint-Bettergrblsupport#117]
**Describe the bug**
it seems this only works with the identifier of _bgs in the printer profiles
**To Reproduce**
Create a duplicate printer profile and the duplicate wont connect.
**Expected behavior**

**Screenshots**

**Logs**
Please provide your octoprint.log and serial.log files.  At the very least copy/paste your terminal tab contents.

**Additional context**

**Comment by synman** [comment]
crap issue with crap details
