### ISSUE TITLE
Z height

### ISSUE THREAD

**Issue by Ofoten3dogcnc** [synman/Octoprint-Bettergrblsupport#2]
Hi, maybe Im missing something, but cant find anywhere to adjust the Z height? Only the X and Y axis :-(

**Comment by thothloki** [comment]
Did you go into the plugin settings and check the box to enable Z?
there is a checkbox with "Show Z Axis on Grbl Control tab"

**Comment by synman** [comment]
Let me track down a screenshot...

**Comment by synman** [comment]
I'm guessing what you really want is Z axis jogging control...

<img width="496" alt="Screen Shot 2019-05-24 at 8 23 41 PM" src="https://user-images.githubusercontent.com/1299716/58362171-183c2380-7e62-11e9-801c-6204c2bf49f1.png">

**Comment by Ofoten3dogcnc** [comment]
Hi :-) 
Yes I did, and it shows the Z height, butthere is no buttons to control the Z height, it just shows the current hight :-(
/Jonna
    På lørdag 25. mai 2019, 01:26:44 CEST skrev thothloki <notifications@github.com> følgende:  
 
 
Did you go into the plugin settings and check the box to enable Z?
there is a checkbox with "Show Z Axis on Grbl Control tab"

**Comment by synman** [comment]
I'll add some z buttons in a future release

**Comment by Ofoten3dogcnc** [comment]
Ok, so there is no way to control the Z axis in this plugin now? How can I then set it to "home"? Is there any other way to do it? :-)
/Jonna
    På lørdag 25. mai 2019, 08:02:43 CEST skrev Shell M. Shrader <notifications@github.com> følgende:  
 
 
I'll add some z buttons in a future release

**Comment by synman** [comment]
You can just plug in a z travel command in the terminal window as a work-around.  Home button currently just goes to x and y 0.  I'll add Z to it as it is no biggy.

Actual homing (exercising your actual end stops if you have them -- the targeting button) is machine specific.  It should home based on your Grbl settings.

**Comment by Ofoten3dogcnc** [comment]
Hi again :-) Any progres on adding the Z height buttons? Thats the only thing missing, in an AWSOME plugin :D

**Comment by synman** [comment]
not yet but I'm (slowly) gearing up for diving back in.   My machine has been collecting dust for a couple months... with it getting cold out I'm sure I'll have some cycles.

**Comment by synman** [comment]
As I don't have a CNC machine / variable Z axis, I want to make sure I've got the homing portion of this correct.

If I set Z0 as part of a home move, will it drive the Z axis into the surface?   I need to understand a little better how Z relates to homing.   

I assume Z0 is calibrated / set based on the spindle being immediately above the surface to cut.

I may delay taking action on the homing aspects of this issue, but this shouldn't prevent me from getting Z travel buttons added for V1.7.0.

**Comment by Ofoten3dogcnc** [comment]
Hi again :-)
Dont think there is a need to home the Z axis, at least what I feel Im missing is a way to control the axis up and down if that is possible to make? When the axis is placed where i want it, I then can home in the Gcode :-)
/Jonna
    På onsdag 6. november 2019, 17:33:35 CET skrev Shell M. Shrader <notifications@github.com> følgende:  
 
 
As I don't have a CNC machine / variable Z axis, I want to make sure I've got the homing portion of this correct.

If I set Z0 as part of a home move, will it drive the Z axis into the surface? I need to understand a little better how Z relates to homing.

I assume Z0 is calibrated / set based on the spindle being immediately above the surface to cut.

I may delay taking action on the homing aspects of this issue, but this shouldn't prevent me from getting Z travel buttons added for V1.7.0.

**Comment by synman** [comment]
I may have this wrapped up tonight (just Z jogging).   As soon as I do, I will process a pull request for v1.7.0 and release everything tagged with the 1.7.0 milestone.

**Comment by Ofoten3dogcnc** [comment]
Thanks, that would be realy awsome :D
/Jonna
    På fredag 8. november 2019, 00:47:23 CET skrev Shell M. Shrader <notifications@github.com> følgende:  
 
 
I may have this wrapped up tonight (just Z jogging). As soon as I do, I will process a pull request for v1.7.0 and release everything tagged with the 1.7.0 milestone.

**Comment by synman** [comment]
How's this look?

<img width="598" alt="Screen Shot 2019-11-07 at 7 49 13 PM" src="https://user-images.githubusercontent.com/1299716/68440045-d4cb3c80-0197-11ea-9597-be9234594e47.png">

**Comment by Ofoten3dogcnc** [comment]
Perfect :-)
    På fredag 8. november 2019, 01:50:29 CET skrev Shell M. Shrader <notifications@github.com> følgende:  
 
 
How's this look?

**Comment by synman** [comment]
ok, one last question.... what GRBL command do you use today for Z jogging?   There are probably 5 different ways I can pull this off....  figure it best to go with the one that works for the requester :)

**Comment by synman** [comment]
I'm just going to go with:

`G1 Z{distance} F4000`

I use a feed rate of 4000 for all the X and Y moves so I assume this speed will work fine for Z too
