### ISSUE TITLE
Smoothieware does not support GRBL config commands

### ISSUE THREAD

**Issue by hgroover** [synman/Octoprint-Bettergrblsupport#26]
I am running a controller board with the Smoothieware firmware. It rejects the $$ command and $ command (see this list for differences from GRBL; https://smoothieware.org/from-grbl and note that the page is incorrect, cat /sd/config.txt is actually the cognate for $$). This plugin offers a lot of essential functionality and the Smoothieboard is not a bad CNC controller. Unfortunately it raises an error on $$ which causes Octoprint to disconnect. Admittedly it is a somewhat knuckleheaded approach in Smoothieware to do a few things differently and not support aliases. I'm reporting this as an issue not because it's a flaw in this plugin but because I believe others may try this with Octoprint + Smoothieware.

**Comment by hgroover** [comment]
I cloned develop and changed a few lines to support Smoothie and it all seems to work locally (except the config parsing, I didn't expect that to work but it doesn't raise an error). The documentation from the Smoothie project was incorrect, cat /sd/config.txt is the correct substitute for $$.

Working on adding the checkbox(es) to enable this behavior into the configuration UI and running more tests, and I can do a PR when I'm done if you're interested. This is a really great plugin and very useful! Currently I've been suffering through the Smoothie native web interface which is not always responsive and doesn't handle large file uploads.

**Comment by synman** [comment]
if you share your code, either here, or via pull request I'm more than happy to add this to the master branch
