### ISSUE TITLE
Uninstall does not restore original Control Tab (And maybe more?)

### ISSUE THREAD

**Issue by technophreak** [synman/Octoprint-Bettergrblsupport#29]
I have uninstalled the plugin and the Control Tab won't come back.

Ideally I wouldn't want to have to reinstall Octoprint from scratch.

**Comment by technophreak** [comment]
I have tried reinstalling latest version Better-Grbl-Support-1.7.1 and uninstall again. 

Same issue.

**Comment by technophreak** [comment]
If anybody else sees this, solution is to edit manually the config file located at /home/pi/.octoprint/config.yaml
Remove the disabled tabs and should be fine.

`
appearance:
    components:
        disabled:
            tab: null
`

**Comment by synman** [comment]
this is documented in the readme

https://github.com/synman/Octoprint-Bettergrblsupport#configuration
