### ISSUE TITLE
Better GRBL support Touch UI

### ISSUE THREAD

**Issue by Pfeifdog** [synman/Octoprint-Bettergrblsupport#36]
Hi. I’m currently using your better GRBL support plugin, on a sandtable project I’m working on. I am trying to use a 3.5” touchscreen as a UI. The standard octoprint UI works with the touchscreen. When I add the GRBL support plugin, the display gets all screwy 😕 Any future plans on making this work with a touchscreen UI?

**Comment by synman** [comment]
I actually use octoscreen with my pi and laser.  I made a couple tweaks to reorder / suppress a couple screens that simply don't apply to GRBL.

**Comment by synman** [comment]
I'm going to close this out since bgs is now fully responsive
