### ISSUE TITLE
When OctoPrint connects to CNC call home

### ISSUE THREAD

**Issue by speedysk1** [synman/Octoprint-Bettergrblsupport#37]
I'm building a sand table and it would be nice to have a way to "auto home" when the plugin connects to the CNC board.  Since, I don't home before processing each gcode drawing.  

Thanks!

**Comment by Pfeifdog** [comment]
I am currently working on the same issue. I wanted to add a touch screen to the rasberryPi, but the better grbll support plugin, doesent display correctly on the screen. There is a (Physical Button) plugin. Which should allow you to push a button to home the axes. But I'm not sure if you can set a button to run a file. My sandtable is all finished. Just trying to make it more user friendly, for those non computer using folks!
