### ISSUE TITLE
Feature: Inputfields for undefined GRBL IDs

### ISSUE THREAD

**Issue by ImagineerNL** [synman/Octoprint-Bettergrblsupport#39]
See enclosed picture; GRBL setting ID 33 is in my case the triggervalue for the G-shock.
However, in other systems, this can be a different value, thats why it is uncommented by default.

It would be a great feature if it was an inputfield, so people can manually document these exceptions for their setup

![image](https://user-images.githubusercontent.com/62603552/137586776-7ddeb1d2-0ba3-472b-81ef-8ea4f5a7d8e8.png)

**Comment by synman** [comment]
you can override this today if you'd like by a simple edit to grbl_settings.txt

https://github.com/synman/Octoprint-Bettergrblsupport/blob/master/octoprint_bettergrblsupport/static/txt/grbl_settings.txt

**Comment by ImagineerNL** [comment]
Works for me :)
thx

**Comment by ImagineerNL** [comment]
well, by making it an inputfield for the 'none' values :)

**Comment by synman** [comment]
lol.... yeah, that covers it functionally... I still have to figure out how to actually manage it behind the scenes.  I keep grbl_settings.txt in sync with GRBL.  Allowing it to be editable deviates from the protocol (purist perspective).   So yeah, it's a bit of refactoring for something I never expected to pop up as an enhancement request.

GRBL is so loosely implemented though, I have to say at this point I'm not all that surprised.

**Comment by synman** [comment]
and wouldn't you know it, with a recent controller board upgrade I performed on my laser engraver (32 bit Black-n-Blue) I am now faced with a similar challenge myself.  

Apparently, the BnB has a ton of documented settings.
<img width="440" alt="Screen Shot 2022-01-19 at 9 33 58 PM" src="https://user-images.githubusercontent.com/1299716/150398265-1f7fe2cf-b9d6-46d1-907a-5351949f43a0.png">
<img width="474" alt="Screen Shot 2022-01-19 at 9 34 14 PM" src="https://user-images.githubusercontent.com/1299716/150398270-7f89a556-36f2-46a9-aa7f-e05ba83509be.png">
<img width="554" alt="Screen Shot 2022-01-19 at 9 34 22 PM" src="https://user-images.githubusercontent.com/1299716/150398274-905b3c50-361a-4a48-ad9d-ea6c4fe8be42.png">

**Comment by ImagineerNL** [comment]
So that means you will implement this feature? :)

**Comment by synman** [comment]
For me, these additional $ settings are pure gibberish and incoherent.  I honestly have no idea what the firmware author was thinking and he will not provide any explanations as to what he was thinking / trying to accomplish.

**Comment by synman** [comment]
there should no longer ANY grbl flavor errors, alarms, and/or settings that are not captured by the plugin.  At this point I have synced up all known variations across core Grbl 1.1, Grbl_Esp32, and FluidNC.
