### ISSUE TITLE
Just an FYI Created a guide for Ortur laser connecting through this plugin

### ISSUE THREAD

**Issue by ImagineerNL** [synman/Octoprint-Bettergrblsupport#40]
Not knowing of a better way to thank you for your tool and letting you know that I created a guide for hooking up an Ortur Laser Master 2 through Octoprint using this plugin.

Your plugin works flawless out of the box, it just takes a bunch of considerations and configurations due to Lightburn and Ortur.

Might work for other lasers as well, but cant test that.

https://www.reddit.com/r/OrturLaserUsers/comments/q7k7nl/guide_octoprint_standalone_engraving_working_for/

https://forum.lightburnsoftware.com/t/guide-octoprint-standalone-engraving-working-for-ortur-laser-master-2/49874

**Comment by synman** [comment]
It would be awesome if you could add this to the wiki.  Let me know if I need to adjust access permissions.  

https://github.com/synman/Octoprint-Bettergrblsupport/wiki

**Comment by ImagineerNL** [comment]
@synman 
https://github.com/synman/Octoprint-Bettergrblsupport/wiki/Guide:-Octoprint-standalone-engraving-working-for-Ortur-Laser-Master-2

**Comment by synman** [comment]
Hey @ImagineerNL,

I read through your walk-thru last night and noted some items that didn't make sense to me, and / or may be unnecessary.  Let me know if you'd like to tweak things / walk through it.

**Comment by ImagineerNL** [comment]
I @synman ,

I looked again; to me it makes sense (or it makes sense that some things make no sense :) )
I dont mind making things a bit more clear, so let me know whats unclear and i will try to fix it

**Comment by synman** [comment]
Thanks for replying.  I've added some comments to the article.  I tried to get markdown to highlight them but it wouldn't let me so you'll find them prefixed with --- and in bold...  I'll try to summarize here:

In Octoprint Settings; Features: Disable Temperature Graph --- The plugin already does this

DO NOT install the 'UI Customiser' plugin, this will break functionality. --- UI Customizer works great - I use it on all my machines

4: Printer Profile --- this changed around v2.0.0 when I introduced the Default Grbl Profile. You need not setup a profile but rather use / edit the one Better Grbl Support provides you. Currently Octoprint ignores all options within the profile (such as the ones listed here) with the exception of the Extruder count. It compares the Extruder count against the tool # provided in gcode and if the tool # in gcode is greater than the extruder count octoprint gets really annoyed. This is why you'll see I've set extruder count to 100

Thanks again for your contributions and I hope this helps!

**Comment by ImagineerNL** [comment]
I will need to re-check my initial workflow then based on the new version.
As soon as i have my laser up&running again i will look into it (currently into relocation of hardware)

I'll reopen this issue and assign myself, else i will forget it

**Comment by ImagineerNL** [comment]
@synman ... nope... i cant do that... can you? :)

**Comment by synman** [comment]
sure thing

**Comment by synman** [comment]
closing this as abandoned
