### ISSUE TITLE
Doesn't work with latest stable Octoprint

### ISSUE THREAD

**Issue by thommy884** [synman/Octoprint-Bettergrblsupport#41]
I have a 3018 pro with a GRBL 0.8 based board. When I tested the plugin the first time everything worked fine. But now, no state is showing and no movement (axis X: n/a, y: n/a etc.) When I connect the router directly to my pc, everything's working fine. But when I use octopi and raspberry, nothing happens except of establishing a sucessfull connection. A fresh reinstall doesn't change anything. Should I use an older octoprint instance instead?

**Comment by conquillacarl** [comment]
You might need to home or unlock before trying to jog. Do you have any status from the terminal or log files?

**Comment by synman** [comment]
not sure if this is valid.  my laser has been dormant for a couple months.   I'll have to track down something to carve and see what I can see

**Comment by synman** [comment]
yeah, so I upgraded to OctoPrint 1.7.2 this evening and am not having any issues.  This plugin has not been tested, nor is it configured for, on python 3.   Perhaps you tried to run it on a system that did not have python 2 installed?
