### ISSUE TITLE
Need Adjustable Weak Laser Setting

### ISSUE THREAD

**Issue by barnold96** [synman/Octoprint-Bettergrblsupport#5]
Clicking on 'Weak Laser' to focus sets laser power to S1.  For my 2.8w laser to come on, I need to be able to set it to S3.  I can do it manually, but can you make the 'Weak Laser' configurable?

**Comment by lathemaster** [comment]
Also allow vale if 0 so you can see the frame and position the material to be engraved

**Comment by synman** [comment]
When I add this, I'll simply make it configurable with a default value of 1.  If you want your weak laser setting to be 0 or 3, or 255 (DOH) you'll be able to just override it in the Plugin Settings panel.

**Comment by synman** [comment]
<img width="513" alt="Screen Shot 2019-11-06 at 10 54 13 AM" src="https://user-images.githubusercontent.com/1299716/68314311-f2a77d00-0083-11ea-9028-a0dbc7a229e5.png">
