### ISSUE TITLE
Draw Frame Box w/o the Laser burning - Enhancement

### ISSUE THREAD

**Issue by lathemaster** [synman/Octoprint-Bettergrblsupport#6]
Totally new to this tech although I do have a CNC machine and a 3D printer.

I am running an NEJE Master 3500 laser for my learning tool
Their firmware is 0.8c GRBL but I assume they have not totally followed the standard.

By "drawing" a frame or bounding box I can tell if 
1. The image used will fit on the material I'm using
2. I can position the material so the image is burned where I need it

**Comment by synman** [comment]
I'm guessing you simply want to not have weak laser enabled when running the bounding box routine.

If so I can accommodate this with addressing another open request to control the weak laser strength.  I believe by allowing a value of zero for laser strength will effectively disable it.
